# 配置tomcat端口号
server:
  port: 8090

spring:
  application:
    name: cloud-template
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

logging:
  level:
    com.alibaba.cloud.nacos: DEBUG