# 配置tomcat端口号
server:
  port: 8090

spring:
  application:
    name: cloud-template
  profiles:
    import: integration_template/nacos.yaml

logging:
  level:
    com.alibaba.cloud.nacos: DEBUG